// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using attendance_service.Infrastructure.Persistence;

#nullable disable

namespace attendance_service.Migrations
{
    [DbContext(typeof(AttendanceDbContext))]
    [Migration("20260608081248_AddAttendanceSession")]
    partial class AddAttendanceSession
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("attendance_service.Domain.Aggregates.AttendanceSession.AttendanceSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CourseSectionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time(6)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("attendance_sessions", (string)null);
                });

            modelBuilder.Entity("attendance_service.Domain.Aggregates.CourseSection.CourseSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CourseSectionCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("LecturerId")
                        .HasColumnType("char(36)");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("course_sections", (string)null);
                });

            modelBuilder.Entity("attendance_service.Domain.Aggregates.Subject.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<Guid?>("FacultyId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("FacultyId");

                    b.ToTable("subjects", (string)null);
                });

            modelBuilder.Entity("attendance_service.Domain.Aggregates.AttendanceSession.AttendanceSession", b =>
                {
                    b.OwnsMany("attendance_service.Domain.Aggregates.AttendanceSession.AttendanceRecord", "Records", b1 =>
                        {
                            b1.Property<Guid>("AttendanceSessionId")
                                .HasColumnType("char(36)");

                            b1.Property<Guid>("StudentId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("char(36)");

                            b1.Property<DateTime?>("CheckedInAt")
                                .HasColumnType("datetime(6)");

                            b1.Property<double?>("Confidence")
                                .HasColumnType("double");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("AttendanceSessionId", "StudentId");

                            b1.HasIndex("StudentId");

                            b1.ToTable("attendance_records", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AttendanceSessionId");
                        });

                    b.Navigation("Records");
                });

            modelBuilder.Entity("attendance_service.Domain.Aggregates.CourseSection.CourseSection", b =>
                {
                    b.OwnsMany("attendance_service.Domain.Aggregates.CourseSection.Enrollment", "Enrollments", b1 =>
                        {
                            b1.Property<Guid>("CourseSectionId")
                                .HasColumnType("char(36)");

                            b1.Property<Guid>("Id")
                                .HasColumnType("char(36)");

                            b1.Property<DateTime>("EnrolledAt")
                                .HasColumnType("datetime(6)");

                            b1.Property<Guid>("StudentId")
                                .HasColumnType("char(36)");

                            b1.HasKey("CourseSectionId", "Id");

                            b1.HasIndex("StudentId");

                            b1.HasIndex("CourseSectionId", "StudentId")
                                .IsUnique()
                                .HasDatabaseName("IX_Enrollment_CourseSectionId_StudentId");

                            b1.ToTable("enrollments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CourseSectionId");
                        });

                    b.OwnsMany("attendance_service.Domain.Aggregates.CourseSection.Schedule", "Schedules", b1 =>
                        {
                            b1.Property<Guid>("CourseSectionId")
                                .HasColumnType("char(36)");

                            b1.Property<Guid>("Id")
                                .HasColumnType("char(36)");

                            b1.Property<string>("DayOfWeek")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)");

                            b1.Property<TimeOnly>("EndTime")
                                .HasColumnType("time(6)");

                            b1.Property<string>("Room")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)");

                            b1.Property<TimeOnly>("StartTime")
                                .HasColumnType("time(6)");

                            b1.HasKey("CourseSectionId", "Id");

                            b1.HasIndex("CourseSectionId", "DayOfWeek", "StartTime")
                                .IsUnique()
                                .HasDatabaseName("IX_Schedule_CourseSectionId_DayOfWeek_StartTime");

                            b1.ToTable("schedules", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CourseSectionId");
                        });

                    b.Navigation("Enrollments");

                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
