// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using attendance_service.Infrastructure.Persistence;

#nullable disable

namespace attendance_service.Migrations
{
    [DbContext(typeof(AttendanceDbContext))]
    partial class AttendanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("attendance_service.Domain.Aggregates.Course.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("attendance_service.Domain.Aggregates.CourseSection.CourseSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("LecturerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SectionCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("course_sessions", (string)null);
                });

            modelBuilder.Entity("attendance_service.Domain.Aggregates.CourseSection.CourseSession", b =>
                {
                    b.OwnsMany("attendance_service.Domain.Aggregates.CourseSection.Enrollment", "Enrollments", b1 =>
                        {
                            b1.Property<Guid>("CourseSessionId")
                                .HasColumnType("char(36)");

                            b1.Property<Guid>("StudentId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("char(36)");

                            b1.Property<DateTime>("EnrolledAt")
                                .HasColumnType("datetime(6)");

                            b1.Property<Guid>("Id")
                                .HasColumnType("char(36)");

                            b1.HasKey("CourseSessionId", "StudentId");

                            b1.ToTable("enrollments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CourseSessionId");
                        });

                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
